AWSTemplateFormatVersion: '2010-09-09'
Description: Hello World with SAM
Resources:
  HelloWorld2Function:
    Properties:
      CodeUri: s3://phc-poc-sam/0774f56be277511bb5f1705d8830a864
      Handler: Hello::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 20
    Type: AWS::Serverless::Function
  HelloWorldFunction:
    Properties:
      CodeUri: s3://phc-poc-sam/a5e2fbb31897d12a2defcea5549ba282
      Handler: Hello::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 20
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
